### ISSUE TITLE
Where did MLPNone go?

### ISSUE THREAD

**Issue by crobertsbmw** [nikolaypavlov/MLPNeuralNet#16]
I was using MLPNone as an activation function on my output layer. I just updated the via CocoaPods and now I am getting an error, `Use of undeclared identifier 'MLPNone'`. Was this removal on purpose?

**Comment by nikolaypavlov** [comment]
@crobertsbmw [MLPNone is in 1.0.10](https://github.com/nikolaypavlov/MLPNeuralNet/blob/8ca786e60993d6e96a176ffb2fb5693c1bdf7a57/MLPNeuralNet/MLPNeuralNet.h#L39). Are you sure you updated it right?

**Comment by crobertsbmw** [comment]
I'm sorry I never returned to this thread. I'm going to close the issue. I don't remember if I had a problem with updating it correctly, or if I manually added it back in. Either way, this is no longer an issue for me.
