### ISSUE TITLE
implement training algorithms ? 

### ISSUE THREAD

**Issue by ArEnSc** [nikolaypavlov/MLPNeuralNet#3]
Hi from what I understand, this is missing the training components for the weight matrices ?

**Comment by ArEnSc** [comment]
Also how do I encode weights for the second layer? 

 NSNumber* inputLayer = [NSNumber numberWithInt:256];
    NSNumber* hiddenLayer = [NSNumber numberWithInt:16];
    NSNumber* outputLayer = [NSNumber numberWithInt:10];
    
    // Matrix includes the bias weight import the matrix from python generated weight matrix.
    double weightMatrix[17][257] // 
double weightMatrix2[11][17] // how do I get the second matrix in there ? 
    
    NSArray* networkConfiguration = @[inputLayer,hiddenLayer,outputLayer];
    
    MLPNeuralNet* neuralNet = [[MLPNeuralNet alloc] initWithLayerConfig:networkConfiguration weights:nil outputMode:MLPClassification];

**Comment by nikolaypavlov** [comment]
> Hi from what I understand, this is missing the training components for the weight matrices ?
Yes. This lib is useful if iOS/OSX is your target platform and you would like to deploy trained models into your product. 
> Also how do I encode weights for the second layer?
In general you should incapsulate them layer by layer into one dimensional nsarray. See for example how to do it if you are using python neuralab package: https://github.com/nikolaypavlov/MLPNeuralNet#python-neurolab

If you can send me a quick example in Python with the package you use, I'll update the docs with the exact solution.

**Comment by ArEnSc** [comment]
I am using the neurolab python solution.
So you are saying assuming a network input = 3 hidden = 3 output = 1 
So assuming the weight matrix is 
Wx between layer 1 and 2 =
[w11 w12 w13] [i 1]
[w21 w22 w23]  [i 2]
[w31 w32 w33]  [i 3]

Wy between layer 2 and 3 = 
new input =  [g11]  [w1 w2 w3 ]
                    [g12]
                    [g13]

So the resulting weight matrix i need for iOS would be
an single double[] = {w11,w12,w13,w21,w22,w23,w31,w32,w33,w1,w2,w3} ?

**Comment by nikolaypavlov** [comment]
There would be always +1 biased neuron for each layer except output. So the actual configuration is  input = 4, hidden = 3, output = 1. On most of the packages including mine biased neurons are implicit. You don't need to specify them during initialization of the layers configuration, but you have to provide correct number of weights.  If you are using python neurolab, just extract the weights with the function I proposed above.

**Comment by nikolaypavlov** [comment]
Note that the actual config of this network: https://github.com/nikolaypavlov/MLPNeuralNet#quick-example is 2->1 (see code example), but it has +1 biased unit and 3 weights. The same story with more complicated network configurations.

**Comment by ArEnSc** [comment]
So is the final result of single double[] = {w11,w12,w13,w21,w22,w23,w31,w32,w33,w1,w2,w3} ? correct ? or incorrect ?

**Comment by nikolaypavlov** [comment]
Incorrect. For 3->3->1 should be (3+1)*3 + (3+1)*1 = 16 weights.

**Comment by ArEnSc** [comment]
The order of the weights is correct though ?

**Comment by nikolaypavlov** [comment]
Inputs connected to the first neuron go first {1b1, w11, w21, w31, than inputs to the second neuron, 1b2, w12, w22, w32, and so on 1b3, w13, w23, w33, next layer, 2b1, w1, w2, w3} = 16 weights in total.

**Comment by nikolaypavlov** [comment]
Here is how you can do it with the example that you send me on email:
```python
import neurolab as nl
import numpy as np

def getweights(net):
     vec = []
     for layer in net.layers:
         b = layer.np['b']
         w = layer.np['w']
         newvec = np.ravel(np.concatenate((b, np.ravel(w,order='F'))).reshape((layer.ci+1, layer.cn)), order = 'F')
         [vec.append(nv) for nv in newvec]
     return np.array(vec)

def createNeuralNet():

    # input vector size 256 = 16 * 16 value input range [0,1];
    featureVector = []
    for i in range(256):
        featureVector.append([0,1])

    neuralNetowrk = nl.net.newff(featureVector,[16,10])
    print "Feature Vector Size: " + str(neuralNetowrk.ci)
    print "Output Vector Size: " + str(neuralNetowrk.co)
    print "Layers: " + str(len(neuralNetowrk.layers))
    
    return neuralNetowrk

net = createNeuralNet()
w = getweights(net)
len(w)
```

You'll get 4282 of weights. Network config is going to be 256->16->10

**Comment by ArEnSc** [comment]
THANK YOU !!! =D
