### ISSUE TITLE
One input unit

### ISSUE THREAD

**Issue by kladis** [nikolaypavlov/MLPNeuralNet#9]
Hello,

Could you please explain in few words what is exactly one specific unit with the weight -30 in your example? 

Thanks in advance!

**Comment by miqizjf25** [comment]
Sorry,I don't know  what the example you have said.

**Comment by nikolaypavlov** [comment]
@kladis it's a weight of the bias unit. If curios what exactly is a bias unit see for example this answer: http://stackoverflow.com/questions/2480650/role-of-bias-in-neural-networks
